### ISSUE TITLE
Examples for Lambas in Now?

### ISSUE THREAD

**Issue by zmarkan** [juicyfx/now-php#15]
Do you have any examples for how to run lambdas in Zeit Now?
I've tried placing scripts in the `api/` directory but keep getting a _not found_ page - the one that PHP renders, not Zeit's one.

**Comment by f3l1x** [comment]
Hi @zmarkan 

Take a look at examples folder - https://github.com/juicyfx/now-php/tree/master/examples

now-php unfortunately doesn't support zero-config, you have to setup `now.json` file.

```json
{
  "version": 2,
  "builds": [
    { "src": "api/**/*.php", "use": "now-php@canary" }
  ]
}
```

**Comment by zmarkan** [comment]
Thanks, that makes sense!

**Comment by f3l1x** [comment]
Examples are moved to solo repository. 

https://github.com/juicyfx/vercel-examples
