### ISSUE TITLE
Environment-variable does not change

### ISSUE THREAD

**Issue by andreasroman** [juicyfx/now-php#22]
First of all, thanks for your work with this, it's really great :slightly_smiling_face:
I have a question about environments, which is not really clear to me.

This is my PHP-file:

```php
<?php

var_dump(getenv('foo'));

phpinfo();
```

I deploy it with now.json:

```json
{
  "version": 2,
  "name": "test",
  "builds": [
    {
      "src": "index.php",
      "use": "now-php"
    }
  ],
  "env": {
    "foo": "foo"
  }
}
```

Thats works as expected and I see string foo dumped with ```getenv()```.

But if I change env foo in ```now.json``` to something else and redeploy it, the value of foo is still foo. It does not change. 

Mabe it's a general problem with now...

**Comment by f3l1x** [comment]
Hi @andreasroman. 

I must discuss it with ZEIT team. Looks like changes in env don't trigger new build. Could you try `now -f`?

**Comment by andreasroman** [comment]
> Hi @andreasroman.
> 
> I must discuss it with ZEIT team. Looks like changes in env don't trigger new build. Could you try `now -f`?

Yes that works :100:
