### ISSUE TITLE
[now dev] $_GET: first argument has "?" as first character

### ISSUE THREAD

**Issue by DevJoghurt** [juicyfx/now-php#4]
Code:
`<?php
var_dump($_GET);`

http://localhost:8080/services/test?test=test&test2=test2

Output:

> array(2) {
>   ["?test"]=>
>   string(4) "test"
>   ["test2"]=>
>   string(5) "test2"
> }

**Comment by f3l1x** [comment]
Should be fixed. Thanks for report.

**Comment by Sugydro** [comment]
Hey. My script does not receive GET requests. What could be the reason?

Config: 
```json
 {
  "version": 2,
  "builds": [
    { "src": "index.php", "use": "now-php" }
  ]
}
```
URL: https://domain.com/index.php?method=random

Code: `<?php
var_dump($_GET);`

Output: 
`array(0) { }`

**Comment by f3l1x** [comment]
Hi @Sugydro. Can you please try it once again?

**Comment by f3l1x** [comment]
There was a issue during refactoring (https://github.com/juicyfx/now-php/commit/1ab298e7bdbbe0c044172ac3e0a66b5d103d33e1). Thanks for pointing me out.

**Comment by Sugydro** [comment]
@f3l1x, still the same :(

**Comment by f3l1x** [comment]
How is that. I've successfully deployed this example (https://github.com/juicyfx/now-php/tree/master/examples/php-test).

Did you try `now -f` to force deploy?

**Comment by Sugydro** [comment]
Oh, now it works, thank you!
