### ISSUE TITLE
Sending email STDERR

### ISSUE THREAD

**Issue by LuisRodriguezLD** [juicyfx/now-php#40]
Hello.
Great repo.
Thanks!!

But I am running into this issue when trying to send an email from a function

`STDERR: sh: /usr/sbin/sendmail: No such file or directory`

**Comment by f3l1x** [comment]
Hi. Sendmail is not supported on ZEIT (AWS lambda). Try to use some mail service. For example https://www.mailgun.com/.

**Comment by LuisRodriguezLD** [comment]
will do, thanks!

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/85281651-ad0cb880-b48a-11ea-8ed0-7db7f8d5082e.png)

https://vercel.com/docs/v2/platform/limits?query=smtp#smtp
