### ISSUE TITLE
502: BAD_GATEWAY

### ISSUE THREAD

**Issue by ehne** [juicyfx/now-php#41]
Hello,
I am trying to deploy a php file.
and it builds fine (I think). But whenever I try to access it, the website gives me a 502 error with the following text : `502: BAD_GATEWAY Code: NO_STATUS_CODE_FROM_FUNCTION`
I've checked the logs and it seems to be an error when it tries to load a shared library (`error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`)

but I'm at a complete loss as to why this has only started to happen today. as it worked fine yesterday. :/

any help would be greatly appreciated.

**Comment by f3l1x** [comment]
It looks like Node 8 has reached EOL.

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

I'm working on new version #37. It will be released today.

**Comment by f3l1x** [comment]
PHP 7.4 and Amazon Linux 2. Done. #37
