### ISSUE TITLE
how to enable php-mcrypt?

### ISSUE THREAD

**Issue by khanhnguyenha1120** [juicyfx/now-php#43]
I need support to enable php-mcrypt on now-php
I get an error when use mcrypt
`Fatal error: Uncaught Error: Call to undefined function mcrypt_module_open() `

Thank you for support.

**Comment by f3l1x** [comment]
Hi @khanhnguyenha1120. 

Mcrypt is not recommended since PHP 7 (https://www.php.net/manual/en/function.mcrypt-module-open.php). 

now-php uses PHP 7.4 under the hood. Try to look for mcrypt provider in packagist (https://packagist.org/packages/phpseclib/mcrypt_compat).

**Comment by khanhnguyenha1120** [comment]
Thank you.

**Comment by f3l1x** [comment]
Closing it now. Feel free to open it again.
