### ISSUE TITLE
add redis v5 extension ?

### ISSUE THREAD

**Issue by thedeadofblackfire** [juicyfx/now-php#56]
# Feature Request

Hi, 

Amazing job, it works like a charm !

I would like to know if you can add the official extension redis v5 on a future release (https://blog.remirepo.net/pages/PECL-extensions-RPM-status) ?

This is the last technical point that I would like to check with a remote redis server for caching php raw data.

Thanks a lot.

Nick

**Comment by f3l1x** [comment]
Hi @thedeadofblackfire. Yum, I will add redis extension, no problemo.

http://pecl.php.net/package/redis

Will let you know, gimme this week pls. :-)

**Comment by thedeadofblackfire** [comment]
Great. The latest 5.2.1 should be perfect. Thanks a lot !

**Comment by f3l1x** [comment]
Added. Take a look https://now-php-mhlhxw910.now.sh/

Just re-deploy your lambdas.

```
now -c -f
```
