### ISSUE TITLE
https://php.jfx.cz/ leaked AWS creds ?

### ISSUE THREAD

**Issue by bitbayio** [juicyfx/now-php#57]
# Bug report
- URL: https://php.jfx.cz/

## Description
I didnt check if they are valid , but your phpinfo(); leaks

AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY 

-- | --

**Comment by f3l1x** [comment]
Hi @bitbayio. Thanks for pointing that, I will work on it.
