### ISSUE TITLE
api/index.php can't be handled by any builder. Make sure it is inside the api/ directory.

### ISSUE THREAD

**Issue by filiptronicek** [juicyfx/now-php#59]
# Bug report

- Version: 0.0.10
- URL: https://maas.filiptronicek.now.sh/
- Repository: https://github.com/filiptronicek/maas

## Description

The function for api/index.php can't be handled by any builder. Make sure it is inside the api/ directory.

I contacted Vercel but they said it's not a problem on their end. Any ideas?

**Comment by f3l1x** [comment]
Hey. I quickly looked at your repo and now.json must be at root folder, not in the api folder.

**Comment by filiptronicek** [comment]
https://github.com/filiptronicek/maas/commit/9d87127450e03164f4d4e4103aa9046fc5d12451#comments

**Comment by filiptronicek** [comment]
![image](https://user-images.githubusercontent.com/29888641/81735965-22ea3100-9496-11ea-86d9-df6fed55ce3c.png)

**Comment by fu-sen** [comment]
Hi @filiptronicek,
I can see your working project:
https://github.com/filiptronicek/maas

I clone this and tried it with Vercel CLI and it is working:
![スクリーンショット 2020-05-13 09 05 07](https://user-images.githubusercontent.com/5434159/81757260-40041b80-94f9-11ea-8fb4-5497127cb629.jpg)

There may be issues specific to your Vercel environment.
Please contact a Vercel member.

**Comment by filiptronicek** [comment]
Thanks for help, I’ll try redeploying and see how it’ll go
